	add_name "LEADER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "RIVAL"
	add_name "ELITE FOUR"
	add_name "ELITE FOUR"
	add_name "LEADER"
	add_name "ELITE FOUR"
	add_name "DELINQUENT"
	add_name "ELITE FOUR"
	add_name "CHAMPION"
	add_name "PALETTE"
	add_name "SCIENTIST"
	add_name "YOUNGSTER"
	add_name "SCHOOLBOY"
	add_name "BIRD KEEPER"
	add_name "LASS"
	add_name "CHEERLEADER"
	add_name "COOLTRAINER"
	add_name "COOLTRAINER"
	add_name "BEAUTY"
	add_name "#MANIAC"
	add_name "ROCKET"
	add_name "GENTLEMAN"
	add_name "SKIER"
	add_name "TEACHER"
	add_name "LEADER"
	add_name "BUG CATCHER"
	add_name "FISHER"
	add_name "SWIMMER"
	add_name "SWIMMER"
	add_name "SAILOR"
	add_name "SUPER NERD"
	add_name "LEADER"
	add_name "GUITARIST"
	add_name "HIKER"
	add_name "BIKER"
	add_name "LEADER"
	add_name "BURGLAR"
	add_name "FIREBREATHER"
	add_name "JUGGLER"
	add_name "BLACKBELT"
	add_name "PSYCHIC"
	add_name "PICNICKER"
	add_name "CAMPER"
	add_name "SAGE"
	add_name "MEDIUM"
	add_name "BOARDER"
	add_name "#FAN"
	add_name "DELINQUENT"
	add_name "TWINS"
	add_name "#FAN"
	add_name "<PKMN> TRAINER"
	add_name "<PKMN> TRAINER"
	add_name "OFFICER"
	add_name "MINER"
	add_name "LEADER"
	add_name "BATTLE"
	add_name "LEADER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "<PKMN> TRAINER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "<PKMN> TRAINER"
	add_name "KIMONO GIRL"
	add_name "LEADER"
	add_name "LEADER"
	add_name "LEADER"
	add_name "TOWER HEAD"
	add_name "TOWER HEAD"
	add_name "TOWER HEAD"
	add_name "<PKMN> TRAINER"
	add_name "GUITARIST"
	add_name "<PKMN> TRAINER"
