	 add_name "MASTER BALL"
	 add_name "ULTRA BALL"
	 add_name "BRIGHTPOWDER"
	 add_name "GREAT BALL"
	 add_name "# BALL"
	 add_name "COAL"
	 add_name "BICYCLE"
	 add_name "MOON STONE" ;8
	 add_name "ANTIDOTE"
	 add_name "BURN HEAL"
	 add_name "ICE HEAL"
	 add_name "AWAKENING"
	 add_name "PARALYZEHEAL"
	 add_name "FULL RESTORE"
	 add_name "MAX POTION"
	 add_name "HYPER POTION" ;10
	 add_name "SUPER POTION"
	 add_name "POTION"
	 add_name "ESCAPE ROPE"
	 add_name "REPEL"
	 add_name "MAX ELIXIR"
	 add_name "FIRE STONE"
	 add_name "THUNDERSTONE"
	 add_name "WATER STONE" ;18
	 add_name "POISON GUARD"
	 add_name "HP UP"
	 add_name "PROTEIN"
	 add_name "IRON"
	 add_name "CARBOS"
	 add_name "LUCKY PUNCH"
	 add_name "CALCIUM"
	 add_name "RARE CANDY" ;20
	 add_name "X ACCURACY"
	 add_name "LEAF STONE"
	 add_name "METAL POWDER"
	 add_name "NUGGET"
	 add_name "# DOLL"
	 add_name "FULL HEAL"
	 add_name "REVIVE"
	 add_name "MAX REVIVE" ;28
	 add_name "GUARD SPEC."
	 add_name "SUPER REPEL"
	 add_name "MAX REPEL"
	 add_name "DIRE HIT"
	 add_name "BURN GUARD"
	 add_name "FRESH WATER"
	 add_name "SODA POP"
	 add_name "LEMONADE" ;30
	 add_name "X ATTACK"
	 add_name "FREEZE GUARD"
	 add_name "X DEFENSE"
	 add_name "X SPEED"
	 add_name "X SPCL.ATK"
	 add_name "COIN CASE"
	 add_name "ITEM FINDER"
	 add_name "HEART SCALE"
	 add_name "EXP. SHARE"
	 add_name "OLD ROD"
	 add_name "GOOD ROD"
	 add_name "SILVER LEAF"
	 add_name "SUPER ROD"
	 add_name "PP UP"
	 add_name "ETHER"
	 add_name "MAX ETHER" ;40
	 add_name "ELIXIR"
	 add_name "CAGE CARD 1"
	 add_name "RIJON PASS"
	 add_name "FERRY TICKET"
	 add_name "CAGE CARD 2"
	 add_name "CAGE CARD 3"
	 add_name "CAGE CARD 4"
	 add_name "MOOMOO MILK" ;48
	 add_name "QUICK CLAW"
	 add_name "PECHA BERRY"
	 add_name "GOLD LEAF"
	 add_name "SOFT SAND"
	 add_name "SHARP BEAK"
	 add_name "CHERI BERRY"
	 add_name "ASPEAR BERRY"
	 add_name "RAWST BERRY" ;50
	 add_name "POISON BARB"
	 add_name "KING'S ROCK"
	 add_name "PERSIM BERRY"
	 add_name "CHESTO BERRY"
	 add_name "RED APRICORN"
	 add_name "TINYMUSHROOM"
	 add_name "BIG MUSHROOM"
	 add_name "SILVERPOWDER" ;58
	 add_name "BLU APRICORN"
	 add_name "SLEEP GUARD"
	 add_name "AMULET COIN"
	 add_name "YLW APRICORN"
	 add_name "GRN APRICORN"
	 add_name "CLEANSE TAG"
	 add_name "MYSTIC WATER"
	 add_name "TWISTEDSPOON" ;60
	 add_name "WHT APRICORN"
	 add_name "BLACKBELT"
	 add_name "BLK APRICORN"
	 add_name "PRZ GUARD"
	 add_name "PNK APRICORN"
	 add_name "BLACKGLASSES"
	 add_name "SLOWPOKETAIL"
	 add_name "PINK BOW" ;68
	 add_name "STICK"
	 add_name "SMOKE BALL"
	 add_name "NEVERMELTICE"
	 add_name "MAGNET"
	 add_name "LUM BERRY"
	 add_name "PEARL"
	 add_name "BIG PEARL"
	 add_name "EVERSTONE" ;70
	 add_name "SPELL TAG"
	 add_name "SILVER EGG"
	 add_name "CRYSTAL EGG"
	 add_name "RUBY EGG"
	 add_name "MIRACLE SEED"
	 add_name "GOLD EGG"
	 add_name "FOCUS BAND"
	 add_name "CONFUSEGUARD" ;78
	 add_name "ENERGYPOWDER"
	 add_name "ENERGY ROOT"
	 add_name "HEAL POWDER"
	 add_name "REVIVAL HERB"
	 add_name "HARD STONE"
	 add_name "LUCKY EGG"
	 add_name "EMERALD EGG"
	 add_name "PRISM KEY" ;80
	 add_name "RED ORB"
	 add_name "GREEN ORB"
	 add_name "STARDUST"
	 add_name "STAR PIECE"
	 add_name "MANSION KEY"
	 add_name "BLUE ORB"
	 add_name "SAPPHIRE EGG"
	 add_name "CURO SHARD" ;88
	 add_name "BEDROOM KEY"
	 add_name "CHARCOAL"
	 add_name "BERRY JUICE"
	 add_name "SCOPE LENS"
	 add_name "MEGAPHONE"
	 add_name "CIGARETTE"
	 add_name "METAL COAT"
	 add_name "DRAGON FANG" ;90
	 add_name "CAGE CARD 5"
	 add_name "LEFTOVERS"
	 add_name "CAGE CARD 6"
	 add_name "EAGULOU BALL"
	 add_name "GIANT ROCK"
	 add_name "LEPPA BERRY"
	 add_name "DRAGON SCALE"
	 add_name "BERSERK GENE" ;98
	 add_name "BLUE FLUTE"
	 add_name "X SPCL.DEF"
	 add_name "CAGE KEY"
	 add_name "SACRED ASH"
	 add_name "REAPER CLOTH"
	 add_name "GOLD TOKEN"
	 add_name "ORE CASE"
	 add_name "DIVE BALL"
	 add_name "FAST BALL"
	 add_name "SMELTER"
	 add_name "LIGHT BALL"
	 add_name "FRIEND BALL"
	 add_name "EVIOLITE"
	 add_name "MACHO BRACE"
	 add_name "BURNT BERRY"
	 add_name "HYPER SHARE"
	 add_name "SUN STONE"
	 add_name "SILK SCARF"
	 add_name "DYNAMITE"
	 add_name "UPGRADE"
	 add_name "ORAN BERRY"
	 add_name "SITRUS BERRY"
	 add_name "DAWN STONE"
	 add_name "GOLD DUST" ;B0
	 add_name "PARK BALL"
	 add_name "IRON PICKAXE"
	 add_name "SHINY STONE"
	 add_name "BRICK PIECE"
	 add_name "RED FLUTE"
	 add_name "YELLOW FLUTE"
	 add_name "BLACK FLUTE"
	 add_name "WHITE FLUTE" ;B8
	 add_name "GREEN FLUTE"
	 add_name "ORANGE FLUTE"
	 add_name "SOOT SACK"
	 add_name "PURPLE FLUTE"
	 add_name "SHOP TICKET"
	 add_name "MINING PICK"
	 add_name "TM CASE"
	 add_name "SAFE GOGGLES" ;C0
	 add_name "RED JEWEL"
	 add_name "BLUE JEWEL"
	 add_name "BROWN JEWEL"
	 add_name "WHITE JEWEL"
	 add_name "PRISM JEWEL"
	 add_name "BIG NUGGET"
	 add_name "HEAT ROCK"
	 add_name "DAMP ROCK" ;C8
	 add_name "SMOOTH ROCK"
	 add_name "ICY ROCK"
	 add_name "LIGHT CLAY"
	 add_name "SHELL BELL"
	 add_name "KEG OF BEER"
	 add_name "FIRE RING"
	 add_name "GRASS RING"
	 add_name "WATER RING" ;D0
	 add_name "THUNDER RING"
	 add_name "SHINY RING"
	 add_name "DAWN RING"
	 add_name "DUSK RING"
	 add_name "MOON RING"
	 add_name "DUSK STONE"
	 add_name "EXPERT BELT"
	 add_name "TRADE STONE" ;D8
	 add_name "SHINY BALL"
	 add_name "ORE"
	 add_name "BURGER"
	 add_name "MUSCLE BAND"
	 add_name "FRIES"
	 add_name "FOSSIL CASE"
	 add_name "SILK"
	 add_name "MAGMARIZER" ;E0
	 add_name "ELECTIRIZER"
	 add_name "PRISM SCALE"
	 add_name "DUBIOUS DISC"
	 add_name "RAZOR CLAW"
	 add_name "RAZOR FANG"
	 add_name "PROTECTOR"
	 add_name "ORNGAPRICORN"
	 add_name "CYANAPRICORN" ;E8
	 add_name "GREYAPRICORN"
	 add_name "PRPLAPRICORN"
	 add_name "SHNYAPRICORN"
	 add_name "WISE GLASSES"
	 add_name "MYSTERY TCKT"
	 add_name "ORPHAN CARD"
	 add_name "QR SCANNER"
	 add_name "GAS MASK" ;F0
	 add_name "FAKE ID"
	 add_name "FLUFFY COAT"
	 add_name "ROOF CARD"
	 add_name "LAB CARD"
	 add_name "GRAPPLE HOOK"
	 add_name "QUICK BALL"
	 add_name "DUSK BALL"
	 add_name "REPEAT BALL" ;F8
	 add_name "TIMER BALL"
	 add_name "MAGNET PASS"
	 add_name "TIME MACHINE"
	 add_name "TOKENTRACKER"
	 add_name "POWER HERB"
	 add_name "ITEM FE"
	 add_name "ITEM FF"
	 add_name "ITEM 0"
