AbilityNames::
	add_name "TORRENT"
	add_name "OVERGROW"
	add_name "BLAZE"
	add_name "PRESSURE"
	add_name "STATIC"
	add_name "LEVITATE"
	add_name "SOUNDPROOF"
	add_name "POISON POINT"
	add_name "EFFECT SPORE"
	add_name "SWARM"
	add_name "SHIELD DUST"
	add_name "LIMBER"
	add_name "LIQUID OOZE"
	add_name "GUTS"
	add_name "CUTE CHARM"
	add_name "FLAME BODY"
	add_name "HYPER CUTTER"
	add_name "INTIMIDATE"
	add_name "CLEAR BODY"
	add_name "ARENA TRAP"
	add_name "DROUGHT"
	add_name "DRIZZLE"
	add_name "SAND STREAM"
	add_name "SNOW WARNING"
	add_name "SYNCHRONIZE"
	add_name "RUN AWAY"
	add_name "MOODY"
	add_name "SPEED BOOST"
	add_name "RIVALRY"
	add_name "TRACE"
	add_name "KLUTZ"
	add_name "EARLY BIRD"
	add_name "SHED SKIN"
	add_name "STURDY"
	add_name "MAGMA ARMOR"
	add_name "STENCH"
	add_name "ILLUMINATE"
	add_name "NO GUARD"
	add_name "WHITE SMOKE"
	add_name "VITAL SPIRIT"
	add_name "INSOMNIA"
	add_name "SNOW CLOAK"
	add_name "SAND VEIL"
	add_name "LIGHTNINGROD"
	add_name "INNER FOCUS"
	add_name "STEADFAST"
	add_name "ICE BODY"
	add_name "FLASH FIRE"
	add_name "ROCK HEAD"
	add_name "HEATPROOF"
	add_name "SNIPER"
	add_name "BATTLE ARMOR"
	add_name "MOLD BREAKER"
	add_name "CHLOROPHYLL"
	add_name "SWIFT SWIM"
	add_name "UNBURDEN"
	add_name "AFTERMATH"
	add_name "OBLIVIOUS"
	add_name "OWN TEMPO"
	add_name "MAGNET PULL"
	add_name "KEEN EYE"
	add_name "STALL"
	add_name "FRISK"
	add_name "THICK FAT"
	add_name "RECKLESS"
	add_name "IRON FIST"
	add_name "SOLID ROCK"
	add_name "SERENE GRACE"
	add_name "NATURAL CURE"
	add_name "LEAF GUARD"
	add_name "SCRAPPY"
	add_name "WATER VEIL"
	add_name "RAIN DISH"
	add_name "TECHNICIAN"
	add_name "MOTOR DRIVE"
	add_name "SUPER LUCK"
	add_name "ADAPTABILITY"
	add_name "WATER ABSORB"
	add_name "VOLT ABSORB"
	add_name "DOWNLOAD"
	add_name "SUCTION CUPS"
	add_name "IMMUNITY"
	add_name "COMPETITIVE"
	add_name "HUSTLE"
	add_name "HUGE POWER"
	add_name "SIMPLE"
	add_name "POISON HEAL"
	add_name "COMPOUNDEYES"
	add_name "MARVEL SCALE"
	add_name "PICKUP"
	add_name "QUICK FEET"
	add_name "AIR LOCK"
	add_name "TINTED LENS"
	add_name "DRY SKIN"
	add_name "TANGLED FEET"
	add_name "CONTRARY"
	add_name "TRUANT"
	add_name "NALJO FURY"
	add_name "SHARPNESS"
	add_name "?????"
