	add_name "POUND"
	add_name "KARATE CHOP"
	add_name "DOUBLE SLAP"
	add_name "FINAL CHANCE"
	add_name "ZEN HEADBUTT"
	add_name "BULK UP"
	add_name "FIRE PUNCH"
	add_name "ICE PUNCH"
	add_name "THUNDERPUNCH"
	add_name "SCRATCH"
	add_name "FAIRY WIND"
	add_name "DRAININGKISS"
	add_name "IRON DEFENSE"
	add_name "SWORDS DANCE"
	add_name "CUT"
	add_name "GUST"
	add_name "WING ATTACK"
	add_name "WHIRLWIND"
	add_name "FLY"
	add_name "BUG BUZZ"
	add_name "NATURE POWER"
	add_name "VINE WHIP"
	add_name "STOMP"
	add_name "DOUBLE KICK"
	add_name "COSMIC POWER"
	add_name "LAUGHING GAS"
	add_name "FLARE BLITZ"
	add_name "SAND ATTACK"
	add_name "HEADBUTT"
	add_name "PRISM SPRAY"
	add_name "POWER BALLAD"
	add_name "BRAVE BIRD"
	add_name "TACKLE"
	add_name "BODY SLAM"
	add_name "WRAP"
	add_name "TAKE DOWN"
	add_name "HAIL"
	add_name "DOUBLE-EDGE"
	add_name "TAIL WHIP"
	add_name "POISON STING"
	add_name "AURA SPHERE"
	add_name "PIN MISSILE"
	add_name "LEER"
	add_name "BITE"
	add_name "GROWL"
	add_name "ROAR"
	add_name "SING"
	add_name "SUPERSONIC"
	add_name "DRAGON PULSE"
	add_name "DISABLE"
	add_name "ACID"
	add_name "EMBER"
	add_name "FLAMETHROWER"
	add_name "MIST"
	add_name "WATER GUN"
	add_name "HYDRO PUMP"
	add_name "SURF"
	add_name "ICE BEAM"
	add_name "BLIZZARD"
	add_name "PSYBEAM"
	add_name "BUBBLE BEAM"
	add_name "FREEZE BURN"
	add_name "HYPER BEAM"
	add_name "PECK"
	add_name "DRILL PECK"
	add_name "LAVA POOL"
	add_name "DRAIN PUNCH"
	add_name "COUNTER"
	add_name "SEISMIC TOSS"
	add_name "STRENGTH"
	add_name "ABSORB"
	add_name "MEGA DRAIN"
	add_name "LEECH SEED"
	add_name "GROWTH"
	add_name "RAZOR LEAF"
	add_name "SOLAR BEAM"
	add_name "POISONPOWDER"
	add_name "STUN SPORE"
	add_name "SLEEP POWDER"
	add_name "HYPER VOICE"
	add_name "STRING SHOT"
	add_name "BULLET PUNCH"
	add_name "FIRE SPIN"
	add_name "THUNDERSHOCK"
	add_name "THUNDERBOLT"
	add_name "THUNDER WAVE"
	add_name "THUNDER"
	add_name "ROCK THROW"
	add_name "EARTHQUAKE"
	add_name "NASTY PLOT"
	add_name "DIG"
	add_name "TOXIC"
	add_name "CONFUSION"
	add_name "PSYCHIC"
	add_name "HYPNOSIS"
	add_name "DRAGON DANCE"
	add_name "AGILITY"
	add_name "QUICK ATTACK"
	add_name "RAGE"
	add_name "TELEPORT"
	add_name "NIGHT SHADE"
	add_name "ENERGY BALL"
	add_name "SCREECH"
	add_name "DOUBLE TEAM"
	add_name "RECOVER"
	add_name "HARDEN"
	add_name "MINIMIZE"
	add_name "SMOKESCREEN"
	add_name "CONFUSE RAY"
	add_name "HEAD SMASH"
	add_name "DEFENSE CURL"
	add_name "BARRIER"
	add_name "LIGHT SCREEN"
	add_name "HAZE"
	add_name "REFLECT"
	add_name "FOCUS ENERGY"
	add_name "ASTONISH"
	add_name "METRONOME"
	add_name "MIRROR MOVE"
	add_name "SELFDESTRUCT"
	add_name "METALLURGY"
	add_name "LICK"
	add_name "SMOG"
	add_name "SLUDGE"
	add_name "THUNDER FANG"
	add_name "FIRE BLAST"
	add_name "WATERFALL"
	add_name "STORM FRONT"
	add_name "SWIFT"
	add_name "AQUA JET"
	add_name "DUST DEVIL"
	add_name "FLASH CANNON"
	add_name "AMNESIA"
	add_name "WILL-O-WISP"
	add_name "SOFT-BOILED"
	add_name "HI JUMP KICK"
	add_name "BURNING MIST"
	add_name "DREAM EATER"
	add_name "POISON GAS"
	add_name "SEED BOMB"
	add_name "LEECH LIFE"
	add_name "SHOCK SMOG"
	add_name "SKY ATTACK"
	add_name "TRANSFORM"
	add_name "BUBBLE"
	add_name "DIZZY PUNCH"
	add_name "SPRING BUDS"
	add_name "FLASH"
	add_name "BASS TREMOR"
	add_name "SPLASH"
	add_name "ACID ARMOR"
	add_name "NIGHT SLASH"
	add_name "EXPLOSION"
	add_name "POISON JAB"
	add_name "SIGNAL BEAM"
	add_name "REST"
	add_name "ROCK SLIDE"
	add_name "METEOR MASH"
	add_name "VOID SPHERE"
	add_name "CONVERSION"
	add_name "TRI ATTACK"
	add_name "DRAGON CLAW"
	add_name "SLASH"
	add_name "SUBSTITUTE"
	add_name "STRUGGLE"
	add_name "CRYSTAL BOLT"
	add_name "WILD CHARGE"
	add_name "THIEF"
	add_name "X-SCISSOR"
	add_name "MIND READER"
	add_name "AERIAL ACE"
	add_name "FLAME WHEEL"
	add_name "IRON HEAD"
	add_name "CURSE"
	add_name "FLAIL"
	add_name "CONVERSION 2"
	add_name "AEROBLAST"
	add_name "COTTON SPORE"
	add_name "REVERSAL"
	add_name "SPITE"
	add_name "POWDER SNOW"
	add_name "PROTECT"
	add_name "MACH PUNCH"
	add_name "SCARY FACE"
	add_name "FEINT ATTACK"
	add_name "SWEET KISS"
	add_name "BELLY DRUM"
	add_name "SLUDGE BOMB"
	add_name "MUD-SLAP"
	add_name "POWER GEM"
	add_name "SPIKES"
	add_name "ZAP CANNON"
	add_name "FORESIGHT"
	add_name "DESTINY BOND"
	add_name "PERISH SONG"
	add_name "ICY WIND"
	add_name "AIR SLASH"
	add_name "DARK PULSE"
	add_name "EARTH POWER"
	add_name "OUTRAGE"
	add_name "SANDSTORM"
	add_name "GIGA DRAIN"
	add_name "ENDURE"
	add_name "CHARM"
	add_name "ROLLOUT"
	add_name "VAPORIZE"
	add_name "SWAGGER"
	add_name "CALM MIND"
	add_name "SPARK"
	add_name "FURY CUTTER"
	add_name "STEEL WING"
	add_name "MEAN LOOK"
	add_name "ATTRACT"
	add_name "SLEEP TALK"
	add_name "HEAL BELL"
	add_name "RETURN"
	add_name "PSYCHO CUT"
	add_name "FRUSTRATION"
	add_name "SAFEGUARD"
	add_name "PAIN SPLIT"
	add_name "SACRED FIRE"
	add_name "MAGNITUDE"
	add_name "DYNAMICPUNCH"
	add_name "MEGAHORN"
	add_name "DRAGONBREATH"
	add_name "BATON PASS"
	add_name "ENCORE"
	add_name "PURSUIT"
	add_name "RAPID SPIN"
	add_name "SWEET SCENT"
	add_name "IRON TAIL"
	add_name "METAL CLAW"
	add_name "MIASMA"
	add_name "MORNING SUN"
	add_name "SYNTHESIS"
	add_name "MOONLIGHT"
	add_name "HIDDEN POWER"
	add_name "CROSS CHOP"
	add_name "TWISTER"
	add_name "RAIN DANCE"
	add_name "SUNNY DAY"
	add_name "CRUNCH"
	add_name "BOIL"
	add_name "SHADOW CLAW"
	add_name "EXTREMESPEED"
	add_name "ANCIENTPOWER"
	add_name "SHADOW BALL"
	add_name "FUTURE SIGHT"
	add_name "ROCK SMASH"
	add_name "STEEL EATER"
	add_name "GHOST HAMMER"
	add_name "MOONBLAST"
	add_name "PLAY ROUGH"
	add_name "NOISE PULSE"
	add_name "@"
